### ISSUE TITLE
good job

### ISSUE THREAD

**Issue by darkdevil87** [GZer/MyKolbot#1]
just to say you good job i have use it whit autosmurf on it and work good but only got probleme whit autoequip he dont very equip good item i think best item are full resis at start for normal and nm but good work i have set it for me and i love your config ;)

**Comment by darkdevil87** [comment]
also sry my bad english im french loll

**Comment by GZer** [comment]
Thanks man. Yeah the Pickit is custom
It is designed for a party of 8 bots so Items are specific to each class
