### ISSUE TITLE
Leader doesn't clear all areas, tries to walk past monsters and chickens out

### ISSUE THREAD

**Issue by eyesima** [GZer/MyKolbot#10]
I have experienced this today when the characters reached Act 3. After leader had Spider Forest WP and started the game at this WP, he just run to the next location (Great Marsh) without killing the monsters around / clearing the area while the followers did a good job on the clearing. As a result, leader was far away and separated from the followers and one of them chickened quite often. 

How can you make that the leader will clear this area? I think there was a similar issue in Harem when they try to get to Arcane.

**Comment by GZer** [comment]
How many are in your party, the leader may have skipped clearing the area because it was too slow for xp or it would often get stuck. Act3 is notoriously bad for changeovers between marshes so it won't bother clearing the area unless it needs a quest item or waypoint.

**Comment by GZer** [comment]
The leader will walk past monsters during act 3 to save time. to change this update your default pather settings to always clear, this will mean most bot movements take longer because they try kill things
