### ISSUE TITLE
Leeches won't join leader games

### ISSUE THREAD

**Issue by GeMiNiJaKe** [GZer/MyKolbot#12]
I don't know why I mean I got it working on another Kolbot and stuck on his AutoSmurf errors..

I can't seem to get leechers to follow the leader, and I already know it's not gonna do levels from scratch due to the other setup doing the exact same..

**Comment by GZer** [comment]
Have you set the leader config in the autolevel section

Example
![image](https://user-images.githubusercontent.com/7009749/70958624-b897b500-20de-11ea-81a9-b28b6dec07ef.png)
