### ISSUE TITLE
MIsses Quests

### ISSUE THREAD

**Issue by TinyHoney** [GZer/MyKolbot#3]
Why they Skip BLood Raven ?

**Comment by GZer** [comment]
Either you haven't told them to or they have bugged out.
Make sure the leader has the correct quest setting in the LevelLeader.js file

**Comment by TinyHoney** [comment]
> 			case 3://BloodRaven
				Pather.journeyTo(17);
				this.clearToQuestLocation(17,1,775);
				this.killQuestBoss(775);
				Pather.getWP(3);
				Pather.journeyTo(1);
				Town.doChores();
				this.logProgress(me.getQuest(2,3),"BloodRaven");

Thats Lines i have. 
 Can change if they out mana then they will go walk ? not wait for mana ?

**Comment by GZer** [comment]
If you are past some waypoints main leader won't bother doing old quests, if you have stony field he won't do Blood Raven.
