### ISSUE TITLE
stuck

### ISSUE THREAD

**Issue by problemseverywhere** [GZer/MyKolbot#4]
hello man im testing it but my problem is that my leader (barb) get stuck with other bots, then he leaves, looks like he wont pass the maggot lair because of that, if i change the leader to a sorc, she wont walk if have no mana for teleport, it could be solved maybe if barb use leap when stuck? i dont know how to do it anyway, what can i do?

**Comment by problemseverywhere** [comment]
oh i checked it and he has staf, i guess eventually he can get it, but have any solution to this?

**Comment by problemseverywhere** [comment]
also in the autoequip pickit had to delete [merctier] because gives error

**Comment by problemseverywhere** [comment]
also the potion buffer sometimes work and sometimes doesnt, i dont know why

**Comment by GZer** [comment]
You need to check your Pather.js file, I updated the barb to use Leap.
Your issues are because there are details in those files that you are missing like the MercTier Auto equip

**Comment by problemseverywhere** [comment]
what i have to change for the merc tier auto equip?
