### ISSUE TITLE
merctier

### ISSUE THREAD

**Issue by problemseverywhere** [GZer/MyKolbot#5]
what i have to change for the merc tier auto equip? if i dont delete the line [merctier] in the pickit i keep getting this error: Unknown 3rd part keyword: merctier

also the bot doesnt seems to dress the merc (which i hired, the bot hire mercs?)

**Comment by problemseverywhere** [comment]
ok i think i solved it, can u answer me if the bot hire merc by his own tho?

**Comment by problemseverywhere** [comment]
so, even though i have fixed the mercier error they don't dress the merc

**Comment by GZer** [comment]
> so, even though i have fixed the mercier error they don't dress the merc

They will only replace items based on lvl and merctier in the autoequip/pickit files.
If these files aren't included then they wont pick up and equip the items
