### ISSUE TITLE
good work but stuck a2 cubing

### ISSUE THREAD

**Issue by ssassassassa** [GZer/MyKolbot#6]
8 player party
the barb pick up quest amu then go for staff
when he try to cube the staff the gamer always crashes
when next game open he restart at Up to Act2; Area:42 the staff quest looking for amu and staff but he have it already in stash...

i already tryed with 3 new partys 
everytime the same stuck Up to Act2; Area:42

its known issue?

**Comment by GZer** [comment]
Pause the bot and throw away the cube, or check that the barb's cube is empty.

He is probably having trouble since there is something left over in his cube which means it won't transmute.

**Comment by ssassassassa** [comment]
thank you for reply
i will check config about cubing items

this time it was working.. bots past a2
now the barb is walking ours around to all a3

what i am missing that the sorc dont tele?
i have to change the sorc to leader?

**Comment by ssassassassa** [comment]
also i still cannot figure out how to forward the script
if i help with selfplay for example to kill duriel the bot start to go again act 2 endles try to do the quests that are done already

**Comment by GZer** [comment]
I've said it multiple times, make sure you copy and dont change the original files unless you know what you're doing. If the Bot is repeating quests it's probably because he is missing something or because he doesnt have a waypoint.
